// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type DiseaseCreate = {
    /**
     * Дата создания записи о болезни
     */
    created_at?: Date;
    patient_id: string;
};

export type DiseasePublic = {
    /**
     * Дата создания записи о болезни
     */
    created_at?: Date;
    id: string;
    patient_id: string;
};

export type DiseasesPublic = {
    data: Array<DiseasePublic>;
    count: number;
};

export type DiseaseUpdate = {
    patient_id?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PatientCreate = {
    /**
     * Полное имя пациента
     */
    full_name: string;
    /**
     * Дата рождения пациента
     */
    birth_date?: (Date | null);
};

export type PatientPublic = {
    /**
     * Полное имя пациента
     */
    full_name: string;
    /**
     * Дата рождения пациента
     */
    birth_date?: (Date | null);
    id: string;
};

export type PatientsPublic = {
    data: Array<PatientPublic>;
    count: number;
};

export type PatientUpdate = {
    full_name?: (string | null);
    birth_date?: (Date | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type LoginLoginAccessTokenData = {
    body: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginLoginAccessTokenError = (HTTPValidationError);

export type LoginTestTokenResponse = (UserPublic);

export type LoginTestTokenError = unknown;

export type LoginRecoverPasswordData = {
    path: {
        email: string;
    };
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginRecoverPasswordError = (HTTPValidationError);

export type LoginResetPasswordData = {
    body: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginResetPasswordError = (HTTPValidationError);

export type LoginRecoverPasswordHtmlContentData = {
    path: {
        email: string;
    };
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type LoginRecoverPasswordHtmlContentError = (HTTPValidationError);

export type UsersReadUsersData = {
    query?: {
        limit?: number;
        skip?: number;
    };
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersReadUsersError = (HTTPValidationError);

export type UsersCreateUserData = {
    body: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersCreateUserError = (HTTPValidationError);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersReadUserMeError = unknown;

export type UsersDeleteUserMeResponse = (Message);

export type UsersDeleteUserMeError = unknown;

export type UsersUpdateUserMeData = {
    body: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdateUserMeError = (HTTPValidationError);

export type UsersUpdatePasswordMeData = {
    body: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersUpdatePasswordMeError = (HTTPValidationError);

export type UsersRegisterUserData = {
    body: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersRegisterUserError = (HTTPValidationError);

export type UsersReadUserByIdData = {
    path: {
        user_id: string;
    };
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersReadUserByIdError = (HTTPValidationError);

export type UsersUpdateUserData = {
    body: UserUpdate;
    path: {
        user_id: string;
    };
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersUpdateUserError = (HTTPValidationError);

export type UsersDeleteUserData = {
    path: {
        user_id: string;
    };
};

export type UsersDeleteUserResponse = (Message);

export type UsersDeleteUserError = (HTTPValidationError);

export type UtilsTestEmailData = {
    query: {
        email_to: string;
    };
};

export type UtilsTestEmailResponse = (Message);

export type UtilsTestEmailError = (HTTPValidationError);

export type UtilsHealthCheckResponse = (boolean);

export type UtilsHealthCheckError = unknown;

export type ItemsReadItemsData = {
    query?: {
        limit?: number;
        skip?: number;
    };
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsReadItemsError = (HTTPValidationError);

export type ItemsCreateItemData = {
    body: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsCreateItemError = (HTTPValidationError);

export type ItemsReadItemData = {
    path: {
        id: string;
    };
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsReadItemError = (HTTPValidationError);

export type ItemsUpdateItemData = {
    body: ItemUpdate;
    path: {
        id: string;
    };
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsUpdateItemError = (HTTPValidationError);

export type ItemsDeleteItemData = {
    path: {
        id: string;
    };
};

export type ItemsDeleteItemResponse = (Message);

export type ItemsDeleteItemError = (HTTPValidationError);

export type PatientsReadPatientsData = {
    query?: {
        limit?: number;
        skip?: number;
    };
};

export type PatientsReadPatientsResponse = (PatientsPublic);

export type PatientsReadPatientsError = (HTTPValidationError);

export type PatientsCreatePatientData = {
    body: PatientCreate;
};

export type PatientsCreatePatientResponse = (PatientPublic);

export type PatientsCreatePatientError = (HTTPValidationError);

export type PatientsReadPatientData = {
    path: {
        id: string;
    };
};

export type PatientsReadPatientResponse = (PatientPublic);

export type PatientsReadPatientError = (HTTPValidationError);

export type PatientsUpdatePatientData = {
    body: PatientUpdate;
    path: {
        id: string;
    };
};

export type PatientsUpdatePatientResponse = (PatientPublic);

export type PatientsUpdatePatientError = (HTTPValidationError);

export type PatientsDeletePatientData = {
    path: {
        id: string;
    };
};

export type PatientsDeletePatientResponse = (Message);

export type PatientsDeletePatientError = (HTTPValidationError);

export type DiseasesReadDiseasesData = {
    query?: {
        limit?: number;
        skip?: number;
    };
};

export type DiseasesReadDiseasesResponse = (DiseasesPublic);

export type DiseasesReadDiseasesError = (HTTPValidationError);

export type DiseasesCreateDiseaseData = {
    body: DiseaseCreate;
};

export type DiseasesCreateDiseaseResponse = (DiseasePublic);

export type DiseasesCreateDiseaseError = (HTTPValidationError);

export type DiseasesReadDiseaseData = {
    path: {
        id: string;
    };
};

export type DiseasesReadDiseaseResponse = (DiseasePublic);

export type DiseasesReadDiseaseError = (HTTPValidationError);

export type DiseasesUpdateDiseaseData = {
    body: DiseaseUpdate;
    path: {
        id: string;
    };
};

export type DiseasesUpdateDiseaseResponse = (DiseasePublic);

export type DiseasesUpdateDiseaseError = (HTTPValidationError);

export type DiseasesDeleteDiseaseData = {
    path: {
        id: string;
    };
};

export type DiseasesDeleteDiseaseResponse = (Message);

export type DiseasesDeleteDiseaseError = (HTTPValidationError);

export type DiseasesReadDiseasesResponseTransformer = (data: any) => Promise<DiseasesReadDiseasesResponse>;

export type DiseasesPublicModelResponseTransformer = (data: any) => DiseasesPublic;

export type DiseasePublicModelResponseTransformer = (data: any) => DiseasePublic;

export const DiseasePublicModelResponseTransformer: DiseasePublicModelResponseTransformer = data => {
    if (data?.created_at) {
        data.created_at = new Date(data.created_at);
    }
    return data;
};

export const DiseasesPublicModelResponseTransformer: DiseasesPublicModelResponseTransformer = data => {
    if (Array.isArray(data?.data)) {
        data.data.forEach(DiseasePublicModelResponseTransformer);
    }
    return data;
};

export const DiseasesReadDiseasesResponseTransformer: DiseasesReadDiseasesResponseTransformer = async (data) => {
    DiseasesPublicModelResponseTransformer(data);
    return data;
};

export type DiseasesCreateDiseaseResponseTransformer = (data: any) => Promise<DiseasesCreateDiseaseResponse>;

export const DiseasesCreateDiseaseResponseTransformer: DiseasesCreateDiseaseResponseTransformer = async (data) => {
    DiseasePublicModelResponseTransformer(data);
    return data;
};

export type DiseasesReadDiseaseResponseTransformer = (data: any) => Promise<DiseasesReadDiseaseResponse>;

export const DiseasesReadDiseaseResponseTransformer: DiseasesReadDiseaseResponseTransformer = async (data) => {
    DiseasePublicModelResponseTransformer(data);
    return data;
};

export type DiseasesUpdateDiseaseResponseTransformer = (data: any) => Promise<DiseasesUpdateDiseaseResponse>;

export const DiseasesUpdateDiseaseResponseTransformer: DiseasesUpdateDiseaseResponseTransformer = async (data) => {
    DiseasePublicModelResponseTransformer(data);
    return data;
};